title: Donald Swen
author: Donald Swen
email: ds3628@columbia.edu
description: A documentation of my journey

github_username:  dswenn
# twitter_username:
# facebook_username:
# dribbble_username:

# date_format:

# google_analytics:
# disqus_shortname:

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll
